apiVersion: v1
kind: Service
metadata:
  name: gateway-out
spec:
  type: NodePort
  ports:
  - port: 5661
    nodePort: 31661
  selector:
    app: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
  - port: 5661
  selector:
    app: gateway
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway  
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - image: weforward/gateway:1.2.7
        name: gateway
        ports:
        - containerPort: 5661
          name: gateway
        env:
        - name: WEFORWARD_PASSWORD
          valueFrom:
             secretKeyRef:
              name: wf-secret
              key: password
        - name: MONGODB_CONNECTION
          value: mongodb://mongodb:27017 
        - name: MONGODB_DB_NAME
          value: wf_gateway
